version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-name: "magenxcommerce/*"
    groups:
      magenxcommerce-modules:
        patterns:
          - "magenxcommerce/*"
    commit-message:
      prefix: deps
